services:
  db:
    container_name: postgres-the-school-system
    image: postgres:latest
    environment:
      POSTGRES_USER: school
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db2:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - network
    restart: unless-stopped
  redis:
    container_name: redis-the-school-system
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    driver: bridge
volumes:
  db2:

