### GET request to example server
//students
GET http://localhost:8081/students
Authorization: Basic YWRtaW46YWRtaW4xMjM=
###
GET http://localhost:8081/students/15

###
GET http://localhost:8081/students/summary/19

###
DELETE http://localhost:8081/students/21
###
POST http://localhost:8081/students
Content-Type: application/json

{
  "name": "ahmed",
  "age": 20
}
###
GET http://localhost:8081/students/specs/18
###
//courses
POST http://localhost:8081/Courses
Content-Type: application/json

{
  "Name": "calc",
  "Level": 3
}
###
GET http://localhost:8081/Courses

###
//assign
PUT http://localhost:8081/students/15/1

###
PATCH http://localhost:8081/students/1
Content-Type: application/json

{
  "name": "rana"
}
###
DELETE http://localhost:8081/students/1
###
GET http://localhost:8081/Staff
###
POST http://localhost:8081/Staff
Content-Type: application/json

{

  "Name": "loging",
  "title": "jwtAuth",
  "password": "thepassword"
}
###
DELETE http://localhost:8081/Staff/1
###
GET http://localhost:8081/Staff
###
PATCH http://localhost:8081/Staff/1
Content-Type: application/json

{
  "Name": "rana",
  "title": "manager"
}

###

//jwt authorization
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "loging",
  "password": "thepassword"
}
###
GET http://localhost:8081/Staff
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsb2dpbmciLCJpYXQiOjE3NzAwNDAzNTIsImV4cCI6MTc3MDA0Mzk1Mn0.66vKUavlT2Y0diGFuaMfCWwFui2QiQlh0gRsEEiYGyFv6aErl6Eq0N_diR4SpeQEGpsdU_ZAN5kvRLkNvzCz6g