### GET request to example server
//students
GET http://localhost:8081/students
Authorization: Basic YWRtaW46YWRtaW4xMjM=
###
GET http://localhost:8081/students/45
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsb2dpbmciLCJpYXQiOjE3NzA1NTI2MzksImV4cCI6MTc3MDU1NjIzOX0.hFGuKeBlZHTs7coSPuUAlnVbZjP4eb2fIo3bdub1UccpeLwSj0PBUxhKbKT_gPNgFElyiMyoCYqkxIO6qMqiuQ

###
GET http://localhost:8081/students/summary/19

###
DELETE http://localhost:8081/students/21
###
POST http://localhost:8081/students
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsb2dpbmciLCJpYXQiOjE3NzA1NTI2MzksImV4cCI6MTc3MDU1NjIzOX0.hFGuKeBlZHTs7coSPuUAlnVbZjP4eb2fIo3bdub1UccpeLwSj0PBUxhKbKT_gPNgFElyiMyoCYqkxIO6qMqiuQ
Content-Type: application/json

{
  "name": "mona",
  "age": 20
}
###
GET http://localhost:8081/students/specs/18
###
//courses
POST http://localhost:8081/Courses
Content-Type: application/json

{
  "Name": "calc",
  "Level": 3
}
###
GET http://localhost:8081/Courses


###
//assign
PUT http://localhost:8081/students/15/1

###
PATCH http://localhost:8081/students/1
Content-Type: application/json

{
  "name": "rana"
}
###
DELETE http://localhost:8081/students/1
###
GET http://localhost:8081/Staff
###
POST http://localhost:8081/Staff
Content-Type: application/json

{

  "name": "admin",
  "title": "administrator",
  "password": "admin321"
}
###
DELETE http://localhost:8081/Staff/1
###
GET http://localhost:8081/Staff
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsb2dpbmciLCJpYXQiOjE3NzExMzcwNTgsImV4cCI6MTc3MTE0MDY1OH0.E3QEaAP5Y_eCF3al1tECYgRI5oDHDjowJYfu30RXpqIDE-CN5iE15TOlEC1hLSJG2sOQ_th3rl5MHy228ce4mw
###
PATCH http://localhost:8081/Staff/1
Content-Type: application/json

{
  "Name": "rana",
  "title": "manager"
}

###

//jwt authorization
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin321"
}
###
GET http://localhost:8081/students
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsb2dpbmciLCJpYXQiOjE3NzA1Mzc5NTQsImV4cCI6MTc3MDU0MTU1NH0.bG1onxD5aR49_imKmVDHE7fDgV8WLX9HNfxv1yY59MNV7gLA4fCJf-YOQtk395Zos_KkLv8trKtHzW-HCnkYTA