### GET request to example server
//students
GET http://localhost:8081/students
Authorization: Basic YWRtaW46YWRtaW4xMjM=
###
GET http://localhost:8081/students/43
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsb2dpbmciLCJpYXQiOjE3NzA1NDYyMzcsImV4cCI6MTc3MDU0OTgzN30.RvdVlyfXBY6kqmek6rmOrU2tawHWVgvFbu2_YJkXwx8hsaYbC_E3x0EzzE0xaN7LYU__E_T5Jz45of6fbKkVqw

###
GET http://localhost:8081/students/summary/19

###
DELETE http://localhost:8081/students/21
###
POST http://localhost:8081/students
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsb2dpbmciLCJpYXQiOjE3NzA1NDYyMzcsImV4cCI6MTc3MDU0OTgzN30.RvdVlyfXBY6kqmek6rmOrU2tawHWVgvFbu2_YJkXwx8hsaYbC_E3x0EzzE0xaN7LYU__E_T5Jz45of6fbKkVqw
Content-Type: application/json

{
  "name": "ali",
  "age": 20
}
###
GET http://localhost:8081/students/specs/18
###
//courses
POST http://localhost:8081/Courses
Content-Type: application/json

{
  "Name": "calc",
  "Level": 3
}
###
GET http://localhost:8081/Courses


###
//assign
PUT http://localhost:8081/students/15/1

###
PATCH http://localhost:8081/students/1
Content-Type: application/json

{
  "name": "rana"
}
###
DELETE http://localhost:8081/students/1
###
GET http://localhost:8081/Staff
###
POST http://localhost:8081/Staff
Content-Type: application/json

{

  "Name": "loging",
  "title": "jwtAuth",
  "password": "thepassword"
}
###
DELETE http://localhost:8081/Staff/1
###
GET http://localhost:8081/Staff
###
PATCH http://localhost:8081/Staff/1
Content-Type: application/json

{
  "Name": "rana",
  "title": "manager"
}

###

//jwt authorization
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "loging",
  "password": "thepassword"
}
###
GET http://localhost:8081/students
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsb2dpbmciLCJpYXQiOjE3NzA1Mzc5NTQsImV4cCI6MTc3MDU0MTU1NH0.bG1onxD5aR49_imKmVDHE7fDgV8WLX9HNfxv1yY59MNV7gLA4fCJf-YOQtk395Zos_KkLv8trKtHzW-HCnkYTA